### PR TITLE
Videos in lists

### PR DESCRIPTION
**Pull request by Nesze**
http://git.svc.ft.com/projects/CP/repos/methode-list-transformer/pull-requests/37/overview

Video part was tested only locally (no video dummy stories exist in Test Methode)
Regression testing was done in pre-prod (lists w articles, blogs).

CC-ed some people recently working on MLT. Please tell if you're fine with us going to prod with this.
@sjwells @yolandeleungFT @peteclark-ft @izzyblues

### CODE REVIEW

**Comment by kovacshuni** [comment]
+1

**Comment by sjwells** [comment]
Need to be sure that we would get an alert that would help people work out what to do if a list couldn't be published because it referenced a video not present in the document store.

I also want to be sure that recent changes haven't impacted publish time (we had those SLA alerts this morning?).

However, other than that, I'm fine with this being merged. Please do it early enough to handle any issues today though :)

**Comment by Nesze** [comment]
We've identified w Yolande the issue which caused the SLA alerts. It's not the publish time nor the changes related to this PR.

The point you've mentioned is also true for blogs, right? Anyway, I'm going to set up an alarm just want to improve a bit the error msg.

It's quite late now, so I'm holding this off until Monday morning.

**Comment by Nesze** [comment]
v27: http://git.svc.ft.com/projects/CP/repos/methode-list-transformer/pull-requests/40/overview

**Pull request merged**
