### PR TITLE
Pre prod

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by Zapadlo** [comment]
+1

**Comment by Nesze** [comment]
+1

Are these recognized by the proxy?

**Comment by catalin-ilea** [comment]
@Nesze Asking this after a +1 ? :)
/usr/local/bin/rest-proxy-docker.sh

for var in $(env | grep -v '^RP_CFG_' | grep '^RP_' | sort); do
  key=$(echo $var | sed -r 's/RP_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${rp_cfg_file}
done

**Comment by catalin-ilea** [comment]
So answer is, yes they are if you follow the right pattern

**Pull request merged**
