### PR TITLE
Implement short heartbeats for read services

### PR DESCRIPTION
**Pull request by Zapadlo**
This is part of the effort to create a read endpoint healthcheck which
would monitor availability of at least one service being available

### CODE REVIEW

**Comment by BerniVarga** [comment]
+1

**Comment by martingartonft** [comment]
Do we want something more lightweight than __health?
Also, please hold off until we get to the bottom of the current mongodb connection issues.

**Comment by Zapadlo** [comment]
@martingartonft We do, but we don't have.

Will hold off :)

**Comment by kovacshuni** [comment]
+1

**Comment by tosan88** [comment]
:+1:

**Comment by martingartonft** [comment]
Can someone remind me what problem this one solves?  I'm nervous about calling healthchecks every few seconds, and also setting etcd value (which required cross-cluster consensus) just as often.

**Comment by Zapadlo** [comment]
Vulcan routing to broken services.

Once the aggregate-healthcheck is able to report on the health of the read services, it will respond as "healthy" as long as an instance of each type of service is available. This means Dyn will route requests that can however fail if an application is running but is unhealthy.

**Comment by martingartonft** [comment]
if we had __gtg, I'd prefer that.  We don't yet in those apps, so this LGTM.

**Comment by Zapadlo** [comment]
Agreed, happy to switch to gtg as soon as thats available

**Comment by Zapadlo** [comment]
Deployed to pre-prod

**Pull request merged**
