### PR TITLE
Enabled sequential/zero-downtime deployment for more apps

### PR DESCRIPTION
**Pull request by tamas-molnar**
Enable zero-downtime deployment (sequentialDeployment) for 
* writers
* transformers/mappers
* read APIs

Full list of apps which now feature ZDD:
```
api-policy-component 
binary-ingester 
binary-writer 
content-preview 
content-public-read-preview 
content-rw-neo4j-blue 
content-rw-neo4j-red 
document-store-api 
enriched-content-read-api 
locations-rw-neo4j-blue 
locations-rw-neo4j-red 
locations-transformer 
memberships-rw-neo4j-blue 
memberships-rw-neo4j-red 
methode-article-transformer 
methode-image-binary-transformer 
methode-image-model-transformer 
methode-list-transformer 
nativerw 
notifications-push 
notifications-rw 
organisations-rw-neo4j-blue 
organisations-rw-neo4j-red 
people-rw-neo4j-blue 
people-rw-neo4j-red 
public-annotations-api 
public-content-by-concept-api 
public-organisations-api 
public-people-api 
public-things-api 
roles-rw-neo4j-blue 
roles-rw-neo4j-red 
sections-rw-neo4j-blue 
sections-rw-neo4j-red 
sections-transformer 
subjects-rw-neo4j-blue 
subjects-rw-neo4j-red 
subjects-transformer 
topics-rw-neo4j-blue 
topics-rw-neo4j-red 
topics-transformer 
v1-annotations-rw-blue 
v1-annotations-rw-red 
v2-annotations-rw-blue 
v2-annotations-rw-red 
varnish 
wordpress-article-transformer 
wordpress-image-mapper 
```

### CODE REVIEW

**Comment by Zapadlo** [comment]
+1

**Comment by khatton-ft** [comment]
I thought this had been discussed and decided there was no need for ZDD for message-driven services? Kafka just buffers incoming events when there is no consumer available.

Having said that I don't think it will do any harm.

**Comment by catalin-ilea** [comment]
Can't remember how deployer works. Will the services get restarted?

**Comment by kovacshuni** [comment]
+1

**Comment by tamas-molnar** [comment]
@catalin-ilea no, the services won't get restarted

**Comment by catalin-ilea** [comment]
lgtm

**Comment by tamas-molnar** [comment]
@khatton-ft good spot, I removed zdd for methode-content-importer. Did you have any other apps in mind?

**Comment by khatton-ft** [comment]
@tamas-molnar wordpress-image-mapper (consumes from NativeCms topic in parallel to content-importer), transformers (now they are invoked by the content-importer), possibly binary-ingester.

**Comment by tamas-molnar** [comment]
Parking this PR until we figure out what happened in XP that blocked the whole deployer...

**Pull request closed without merging**
