### PR TITLE
Bump v1-suggestor to 0.0.10

### PR DESCRIPTION
**Pull request by tamas-molnar**
Changes since 0.0.8:
* https://github.com/Financial-Times/v1-suggestor/pull/14
* https://github.com/Financial-Times/v1-suggestor/pull/16 - tried in XP

### CODE REVIEW

**Comment by tosan88** [comment]
Financial-Times/v1-suggestor#14 - tried in XP, works

**Comment by tosan88** [comment]
:+1:

**Comment by catalin-ilea** [comment]
lgtm

**Comment by Zapadlo** [comment]
+1

**Pull request merged**
