### PR TITLE
restart mongodb on failure

### PR DESCRIPTION
**Pull request by Nesze**

### CODE REVIEW

**Comment by Zapadlo** [comment]
+1

**Comment by Nesze** [comment]
shhh, I've just forgotten to merge this to pre-prod first

**Comment by Zapadlo** [comment]
What I tend to do is: raise a PR for master, then checkout pre-prod, merge and push myself. Then I can say "tested in pre-prod" on my master PR.

ymmv

**Comment by Nesze** [comment]
Good enough for me

**Pull request merged**
