### PR TITLE
Notifications push w xp

### PR DESCRIPTION
**Pull request by kovacshuni**

### CODE REVIEW

**Comment by Nesze** [comment]
+1

**Comment by Zapadlo** [comment]
Hate to be rehashing the same thing all the time, but why base `xp` for the PR?

**Comment by kovacshuni** [comment]
No, George, this is more misleading than that. The branch _notifications-push_ is based on master. Then for to be able to create the most lightweight PR to merge to _xp_ i created a branch that merges already _xp_ and _notifications-push_ so conflicts can be resolved beforehand. So merging _notifications-push-w-xp_ is just a fast-forward merge to _xp_.

**Comment by Zapadlo** [comment]
Understood, thanks!

**Pull request merged**
