### PR TITLE
Versioning content-ingester

### PR DESCRIPTION
**Pull request by tosan88**
`services.yaml` defines a version but the service file of content-ingester did not support it. Fixing it now with this commit

### CODE REVIEW

**Comment by Nesze** [comment]
+1

**Comment by Zapadlo** [comment]
+1

**Comment by tamas-molnar** [comment]
+1

**Comment by martingartonft** [comment]
+1

**Comment by tosan88** [comment]
Tested in xp. Going to pre-prod

**Comment by tosan88** [comment]
Pre-prod is ok. Going to merge to master

**Pull request merged**
