### PR TITLE
Add unique container names for kafka-related services 

### PR DESCRIPTION
**Pull request by tosan88**
Also please note:
`kafka-rest-proxy` reworked to be templated as in [pub-services-files](https://github.com/Financial-Times/pub-service-files/blob/master/kafka-rest-proxy%40.service)

### CODE REVIEW

**Comment by kovacshuni** [comment]
+1

**Comment by tosan88** [comment]
Note: While testing in XP I noticed kafka/zookeper docker instance remained there - which caused the new instance to start up correctly

**Comment by catalin-ilea** [comment]
+1

**Comment by BerniVarga** [comment]
+1

**Pull request merged**
