### PR TITLE
Release new version of vulcan

### PR DESCRIPTION
**Pull request by Zapadlo**
Allows unhealthy start up.

### CODE REVIEW

**Comment by Zapadlo** [comment]
Letting it soak in `xp` for a while

**Comment by tosan88** [comment]
+1

Though, strangely, the latest vulcand build failed: https://hub.docker.com/r/coco/vulcand/builds/bjwtkzjku6jegtzbkk5ftsv/ but nonetheless ft-vulcan was successfully built: https://hub.docker.com/r/coco/ft-vulcan/builds/bwfklkl25i9ektyikwzg46y/

**Comment by kovacshuni** [comment]
+1

**Comment by Zapadlo** [comment]
@tosan88 We don't use that build for anything, its also 264M where `ft-vulcan` docker build is 7M. If we are looking to fork we might just replace vulcan's `Dockerfile` with our own based on `alpine`.

**Comment by martingartonft** [comment]
+1.  Is this going up-stream? link?

**Comment by Zapadlo** [comment]
@martingartonft https://github.com/vulcand/vulcand/pull/287

**Comment by Zapadlo** [comment]
Pushed to `pre-prod`

**Pull request merged**
