### PR TITLE
Feature/enable neo4j http logging

### PR DESCRIPTION
**Pull request by duffj**

### CODE REVIEW

**Comment by khatton-ft** [comment]
only for red?

**Comment by duffj** [comment]
Yep, just for now, until I can get it working.

**Comment by duffj** [comment]
The PR for `master` will be for red and blue.

**Comment by khatton-ft** [comment]
Makes sense. I hadn't spotted this PR wasn't for master.
:+1:

**Comment by duffj** [comment]
@khatton-ft thanks. I should make it clear that this is a totally temporary solution taken from https://neo4j.com/developer/docker-23/ which allows us to override specific config items. It's not actually production-ready at all. We'll have to come up with a significantly better (more automated and more surgical) way of overriding config to enable request logging before it's ready to deploy to prod. So this is more of a prototyping solution to see how helpful request logging is.

And actually, with the problem we're currently looking at, it hasn't been needed (so far).

**Comment by tosan88** [comment]
:+1:

**Comment by nwrigh** [comment]
We now use config files for configuration of Neo not this method

**Pull request closed without merging**
