### PR TITLE
Bumped version to deploy correction to uuid creation in Topics Transformer

### PR DESCRIPTION
**Pull request by nwrigh**

### CODE REVIEW

**Comment by BerniVarga** [comment]
+1

**Comment by nwrigh** [comment]
:+1:

**Comment by Zapadlo** [comment]
Did you... upvote your own PR? :)

**Comment by tosan88** [comment]
Maybe she likes that Berni upvoted it :)

**Comment by nwrigh** [comment]
I was super tired yesterday with lots of PR's .... It's given me a laugh now!

**Pull request merged**
