### PR TITLE
Change the service files to support graphite configuration

### PR DESCRIPTION
**Pull request by sjwells**
I also fixed the HOST_HEADER which was really the QUEUE_ID

### CODE REVIEW

**Comment by khatton-ft** [comment]
You need to define `$ENV` (cf api-policy-component@.service).

**Comment by sjwells** [comment]
Thanks Keith. I have made that change now!

**Comment by khatton-ft** [comment]
:+1:

**Comment by tosan88** [comment]
I assume you will change the version too once your PR on concept-ingester is released, so
 :+1:

**Comment by sjwells** [comment]
Yes - thanks for reminded me, but that is what I will do

**Pull request merged**
