### PR TITLE
Making sure backends don't expire for content publish pipeline

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by tamas-molnar** [comment]
lgtm

**Comment by BerniVarga** [comment]
+1

**Comment by tosan88** [comment]
You might want to modify binary-writer-sidekick too

**Comment by catalin-ilea** [comment]
@tosan88 I intentionally left it out because we need to modify binary ingester healtchecks not to use dw admin port before I can make these changes

**Comment by tosan88** [comment]
:+1:

**Comment by Zapadlo** [comment]
+1

**Pull request merged**
