### PR TITLE
Special-reports-rw-neo4j services

### PR DESCRIPTION
**Pull request by tosan88**
* https://github.com/Financial-Times/special-reports-rw-neo4j

### CODE REVIEW

**Comment by kovacshuni** [comment]
+1

**Comment by BerniVarga** [comment]
Tested in XP.

**Comment by catalin-ilea** [comment]
Can you please follow this pattern for sidekicks? https://github.com/Financial-Times/up-service-files/blob/master/enriched-content-read-api-sidekick%40.service

**Comment by tosan88** [comment]
@catalin-ilea done

**Comment by catalin-ilea** [comment]
lgtm

**Pull request merged**
