### PR TITLE
Lower resource usage by mongodb backup

### PR DESCRIPTION
**Pull request by martingartonft**
Use newer version which uses newer Go version and had simplified code,
both of which reduce CPU overhead.

Also, limit memory to 1g in the docker command.

### CODE REVIEW

**Comment by tosan88** [comment]
:+1:

**Comment by khatton-ft** [comment]
Latest version built by Jenkins was v19!

**Comment by martingartonft** [comment]
I wonder why 13 was the one in use?

Anyway, happy to re-release as v20.0.0 and update here if we think it matters?

**Comment by khatton-ft** [comment]
v18 is in use in Dynpub, but hasn't yet made it to production. I believe you created v19 :)

**Comment by martingartonft** [comment]
I didn't realise the dynpub stuff was not in prod yet, sorry.

I'll hold off deploying this anywhere else and re-version this once dynpub stuff is in prod. I may have more changes by then anyway.

**Pull request merged**
