### PR TITLE
v1.0.8

### PR DESCRIPTION
**Pull request by Zapadlo**
https://github.com/Financial-Times/aggregate-healthcheck/releases/tag/v1.0.8

### CODE REVIEW

**Comment by catalin-ilea** [comment]
lgtm

**Comment by Zapadlo** [comment]
Deployed to `xp`

**Comment by Zapadlo** [comment]
Deploy to `pre-prod`

**Comment by catalin-ilea** [comment]
Is it safe to deploy this to prod?

**Pull request merged**
