### PR TITLE
Fixed missing PORT and LB member check

### PR DESCRIPTION
**Pull request by Zapadlo**
PORT getting is done inside the loop, but `docker port` only gets called
if $PORT is empty, once populated value is reused

Also checks healthchecks of the main service, if all are true, sets the
value in etcd

### CODE REVIEW

**Comment by kovacshuni** [comment]
+1

**Comment by tosan88** [comment]
:+1:

**Comment by tamas-molnar** [comment]
Is `jq` included in CoreOs by default?

**Comment by Zapadlo** [comment]
@tamas-molnar Yep, very happy about that

**Comment by tamas-molnar** [comment]
+1

**Comment by Zapadlo** [comment]
Deployed to xp

**Comment by catalin-ilea** [comment]
Can we add the same thing on varnish?

**Comment by Zapadlo** [comment]
The port - yes, it doesn't have healthchecks, does it?

**Comment by catalin-ilea** [comment]
Check __health as well. It will hit api-component-policy/__health but it will tell us if varnish is running. Bad idea?

**Comment by Zapadlo** [comment]
Yes... you are going to hammer ACP/__health every 2.5 seconds. Is varnish likely to run broken?

**Comment by catalin-ilea** [comment]
Probaly not. Ok, fair point, leave it as is.

**Comment by Zapadlo** [comment]
Deployed to `pre-prod`

**Pull request merged**
