### PR TITLE
New service for registering cluster tunnel in dns

### PR DESCRIPTION
**Pull request by Zapadlo**
https://github.com/Financial-Times/coco-provisioner/pull/51

To go with this PR, placing konstructor API key in etcd

This will register the machine running the service in Dyn as a `$ENV-tunnel.up.coco.ft.com`. Currently `update` does not work, blocked by Akamai. To be resolved soon.

### CODE REVIEW

**Comment by catalin-ilea** [comment]
Nice. Can we eventually do the same with $ENV.up.coco.ft.com ?

**Comment by Zapadlo** [comment]
:D Thats the idea, tunnel is simple and innocent enough to verify this.

**Comment by catalin-ilea** [comment]
Cool. lgtm

**Comment by Nesze** [comment]
+1

**Comment by Zapadlo** [comment]
Merged outside of this PR

**Pull request closed without merging**
