### PR TITLE
Changing healthcheck directory structure to include service instances…

### PR DESCRIPTION
**Pull request by tosan88**
… separately

### CODE REVIEW

**Comment by Zapadlo** [comment]
+1

Could you possibly do the other three as well? I haven't even started on those :((

**Comment by martingartonft** [comment]
lgtm

**Comment by tosan88** [comment]
Sure, I will do the same for the other 3 service as well ;)

**Comment by Zapadlo** [comment]
Thanks so much dude!

**Comment by tosan88** [comment]
Changed for the rest of the services. Also included a missing change for the first part of the pull request.

**Comment by Zapadlo** [comment]
Cool! +2

**Pull request merged**
