### PR TITLE
Removing vulcan auth params

### PR DESCRIPTION
**Pull request by tamas-molnar**
* tried in XP, bridges work

### CODE REVIEW

**Comment by catalin-ilea** [comment]
lgtm

**Comment by martingartonft** [comment]
+1

**Comment by tosan88** [comment]
:+1: 
Just FYI: `prod-us` still has the key `/ft/_credentials/vulcand/authorization_header`

**Comment by tamas-molnar** [comment]
@tosan88 thanks, I'll remove it

**Pull request merged**
