### PR TITLE
param api_host will be set in etcd when custer gets provisioned

### PR DESCRIPTION
**Pull request by JuliaFernee**

### CODE REVIEW

**Comment by JuliaFernee** [comment]
this PR is related to this PR: https://github.com/Financial-Times/coco-provisioner/pull/113

**Comment by catalin-ilea** [comment]
Are you manually doing etcdctl set /ft/config/api_host "env-specific-api-host" on every cluster before deploying this?

**Comment by catalin-ilea** [comment]
lgtm

**Comment by khatton-ft** [comment]
:+1:

**Pull request merged**
