### PR TITLE
Added binding-service-specific v1-content-annotators

### PR DESCRIPTION
**Pull request by tamas-molnar**
* needed to process the messages coming from the binding-service, see UPP-1262
* only change from the existing v1-content annotators is the `-env "ANNOTATING_SYSTEM=http://cmdb.ft.com/systems/binding-service"`
* tested in XP, works
* these will be removed when the existing V1-metadata publish flow will be decommed (the one which goes through preditor)

### CODE REVIEW

**Comment by martingartonft** [comment]
+1

**Comment by tosan88** [comment]
The kafka group ids should be different than for existing services...

**Comment by tamas-molnar** [comment]
Good spot @tosan88, changed!

**Comment by tosan88** [comment]
:+1:

**Pull request merged**
