### PR TITLE
Updating neo4j to use an EBS.

### PR DESCRIPTION
**Pull request by carlosroman**

### CODE REVIEW

**Comment by Zapadlo** [comment]
Has this been addressed yet? https://github.com/Financial-Times/coco-provisioner/pull/89#issuecomment-202973290

**Comment by carlosroman** [comment]
This is a work in progress branch. PR was because I wanted to link to a bit of code and found it easier to do it that way.

**Comment by Zapadlo** [comment]
Ah okay, good to know.

**Comment by carlosroman** [comment]
Giving up on this.

**Pull request closed without merging**
