### PR TITLE
Limit ingester services to 512M memory

### PR DESCRIPTION
**Pull request by Zapadlo**

### CODE REVIEW

**Comment by Nesze** [comment]
+1

**Comment by kovacshuni** [comment]
+1

**Comment by khatton-ft** [comment]
The ingester Dockerfile specifies `-Xmx1024m` so it will be interesting to see how those play together.

**Comment by Zapadlo** [comment]
Thats interesting...

Should we limit systemd unit files to 1G instead?

I don't know what would happen, as far as service is concerned it will think it is running on a box with 512M ram.

**Comment by khatton-ft** [comment]
If it uses that much memory then I'd guess the JVM will eventually throw OOM errors. Going forward, the ingester will be receiving and handling larger messages (content JSON in payload).

It's worth trying this out to see what happens. If there aren't any problems we should update the Dockerfile to match, otherwise maybe you'll need to increase the memory here.

What if any is the current limit?

**Comment by Zapadlo** [comment]
There isn't, omitting it defaults to `infinity` which is box's max ram, so in our case 8G. Which is why we are getting warnings about low memory as java apps and vulcan are eating several Gs.

**Comment by khatton-ft** [comment]
So in that case :+1: but monitor carefully.

**Comment by kovacshuni** [comment]
I think forcing it from the outside (service file) will not bring good times. It would be much better to limit the java apps' memory by the Xmx flags, that way it will try to stay low by itself. Of course the setting in the service file can remain, but that would be just like a safety net, a strict barrier.

**Comment by Zapadlo** [comment]
Problem is `Xmx` does not actually limit the memory usage of the app to that value.

**Comment by martingartonft** [comment]
should we default to not specifying heap parameters and letting java decide (including deciding based on limits presented by docker)

**Comment by Zapadlo** [comment]
http://git.svc.ft.com/projects/CP/repos/ingester/pull-requests/56/overview

**Comment by Zapadlo** [comment]
Deployed to XP

**Comment by kovacshuni** [comment]
cool stuff

**Comment by Zapadlo** [comment]
Deployed to pre-prod

**Pull request merged**
