### PR TITLE
Add identifiers people-rw take 2

### PR DESCRIPTION
**Pull request by nwrigh**
Second attempt at a PR after merge conflicts caused a redo. The original that is completely tested: https://github.com/Financial-Times/up-service-files/pull/635

### CODE REVIEW

**Comment by BerniVarga** [comment]
+1

**Comment by tosan88** [comment]
:+1:

**Comment by nwrigh** [comment]
:+1:  @tosan88

**Comment by scott-ace-newton** [comment]
:+1:

**Pull request merged**
